### ISSUE TITLE
GFX_demo fails to compile - bad constructor call

### ISSUE THREAD

**Issue by Andy2No** [mvniemi/Linksprite_EP2P04#1]
Hi,

Possibly I'm misunderstanding how this is meant to be installed and used, with the Arduino IDE, but I can't get the GFX_demo example to compile.

I first tried opening the examples as sketches, but that meant the IDE couldn't find the Linksprite_EP2P04.h include file for GFX_demo, so I copied the folder into ..\Arduino\libraries.  I now get this error, when I try to compile it:

GFX_demo:8: error: no matching function for call to 'Linksprite_EP2P04::Linksprite_EP2P04(int)'
Linksprite_EP2P04 display(1);

The constructor in the include file appears to require several arguments (not just the one given here), which are not optional, so either I'm looking at the wrong include file (and so is the IDE) or something is wrong with the example code.

I did manage to get the write_buffer_only example compiled and running on a Leonardo, though I had to comment out the Serial.begin(9600); line - which doesn't appear to do anything useful, and for some reason, stopped it running.

Also, I had to isntall the Adafruit graphics library (Adafruit-GFX-Library).  That might be obvious to some people, but it should probably get a mention in the readme, to give the rest of us a clue.  If it was documented, I didn't see it.

**Comment by mvniemi** [comment]
Hey Andy,
My apologies, the example files in the library are definitely from an older version and will not work. I am currently traveling today, but I'll try to get an updated version pushed asap, along with some documentation.

**Comment by Andy2No** [comment]
Great.  Thanks.  I'll look forward to it.

I expect the write_buffer_only one works as is, on anything other than a Leonardo - I'm still not clear why I had to remove the Serial.begin() but I'm not really used to them.  It was all I had to hand.  It was good to see that work, anyway.

Mine came with something on the screen resembling a luggage label, in English.  I ran the example sketch from the manufacturers site - after changing unsigned char PROGMEM gImage[3096]  to **const** unsigned char PROGMEM gImage[3096], to get it to compile.  That changed it to something similar, but in Chinese.

**Comment by Andy2No** [comment]
I've hacked a semi-functional version of your GFX_demo example - semi functional because the screen seems to update when it wants, not when I expect it to, and I'm having to reset the Leonardo after uploading it to get it to run, most of the time - not what I expected, but maybe just a Leonardo thing?

It seems it probably should provide a way of checking the status of the display chip, before sending more data - or letting the user code check it, at least.  Failing that, it seems to need surprisingly long delays between writes to the screen.

Also, I note you've allocated a buffer that's only big enough for monochrome, but the code calculates the maximum buffer length based on the mode - so you'll get buffer overruns if you try to use the greyscale mode.

In Linksprite_EP2P04.cpp you have this:

<pre>
unsigned char buff[1548];

//...

    if (_mode == 1){buffsize = EP2P04_LCDHEIGHT*EP2P04_LCDWIDTH/4;}
    else {buffsize = EP2P04_LCDHEIGHT*EP2P04_LCDWIDTH/8;}**
</pre>

- In greyscale mode, buffsize is calculated to be twice what you've allocated for the buffer.

Anyway, here's the modified demo sketch.  Feel free to use it, if you want to:

{Edit:  Sorry; I have no idea how to get a normal CODE block displayed here}

<pre>
#include &lt;Adafruit_GFX.h&gt;
#include &lt;Linksprite_EP2P04.h&gt;
//include "Arduino.h"

//172*72

#define MONO 0
#define FOURTONE 1

//Linksprite_EP2P04 display(1);   - wrong version!

// Pins definitions, based on image of underside of board
const uint8_t DC = 8;
const uint8_t STAT = 9;
const uint8_t CS = 10;
  // DA appears to be MOSI
const uint8_t DA = 11;
  // RS appears to be RES
const uint8_t RS = 12;
// redefinition of 'const uint8_t SCK'
const uint8_t SCKpin = 13;
  // ATmega328 wouldn't have enough memory for four tone greyscale
const uint8_t MODE = MONO;

//    Linksprite_EP2P04(uint8_t DC, uint8_t STAT, uint8_t CS, uint8_t DA, uint8_t RS, uint8_t SCK, uint8_t MODE);
Linksprite_EP2P04 EinkDisplay(DC, STAT, CS, DA, RS, SCKpin, MODE);

#define BLACK 1
#define WHITE 0

const int serialMonitor= false;

void setup() {
    if(serialMonitor) Serial.begin(9600);
    EinkDisplay.begin();
 //EinkDisplay.write_buffer_mono();

 /* EinkDisplay.clearDisplay();  
 EinkDisplay.refresh(); delay(1500); */
 
 // Write the supplied image directly to the display (no need to refresh)
 EinkDisplay.image_display(); // I can't get this to work if I clear the screen first
 delay(3500); // allow at least some time for it to finish - status doesn't appear to be checked
              // - no idea how long, probably less than this, but leave it on the screen long enough to notice
 
 EinkDisplay.clearDisplay();  // Only clears the buffer - call refresh() afterwards
 EinkDisplay.refresh(); delay(500); 
 
 /* EinkDisplay.fillBlack();
 EinkDisplay.refresh(); delay(500); */

 /* EinkDisplay.clearDisplay();
 EinkDisplay.refresh(); delay(500); */


 for(int line=0; line< 4; line++)
 {
   EinkDisplay.setCursor(0, line<<3);
   EinkDisplay.setTextColor(line);  // 0 is white
   EinkDisplay.print("Hello, inky world... "); EinkDisplay.print(line);
 }
 EinkDisplay.refresh(); delay(3000);  // I expect to see the text for a while, before the next bit, 
                                      // but that doesn't happen if it's much less than three seconds

 for(int i =0; i<72; i++){
   EinkDisplay.drawPixel(i, i, i%4);
 }
 EinkDisplay.refresh(); delay(500);
 
    delay(3000);
    EinkDisplay.clearDisplay();
    EinkDisplay.refresh();
    
    testdrawrect(1);
    delay(1000);
    EinkDisplay.refresh();
//    EinkDisplay.clearDisplay();
//   testdrawchar();
   // EinkDisplay.write_buffer_color();    // Has to have a parameter!
//    EinkDisplay.refresh();
//    delay(2000);
//    EinkDisplay.clearDisplay();
//    EinkDisplay.fillBlack();
//    EinkDisplay.refresh();
//    delay(1000);
    //te0stdrawrect(BLACK);
//    EinkDisplay.refresh();
//    delay(100);
//    EinkDisplay.clearDisplay();
//    EinkDisplay.fillBlack();
//    //testdrawrect(0);
//    EinkDisplay.refresh();
  if(serialMonitor) while(!Serial) ;  // for Leonardo
}


void printbuffer(char buf[]){
  for (int i=0 ; i < (72*172/8); i++){
    PrintHex8(&buf[i],1);
  }
  if(serialMonitor) Serial.println("");
  
}
void loop() {
  // put your main code here, to run repeatedly:
  


}

void testdrawrect(int color) {
  for (uint8_t i=0; i<EinkDisplay.height()/2; i+=2) {
    EinkDisplay.drawRect(i, i, EinkDisplay.width()/2-2*i, EinkDisplay.height()-2*i, color);
    EinkDisplay.refresh();
  }
}

void testdrawcircle(void) {
  for (uint8_t i=0; i<EinkDisplay.height(); i+=2) {
    EinkDisplay.drawCircle(EinkDisplay.width()/2-5, EinkDisplay.height()/2-5, i, BLACK);
    EinkDisplay.refresh();
  }
}

void PrintHex8(uint8_t *data, uint8_t length) // prints 8-bit data in hex with leading zeroes
{
     char tmp[16];
       if(serialMonitor) for (int i=0; i<length; i++) { 
         sprintf(tmp, "0x%.2X",data[i]); 
         Serial.print(tmp); Serial.print(",");
       }
}

void testdrawchar(void) {
  EinkDisplay.setTextSize(1);
  EinkDisplay.setTextColor(WHITE);
  EinkDisplay.setCursor(0,0);

  for (uint8_t i=0; i < 168; i++) {
    if (i == '\n') continue;
    EinkDisplay.write(i);
    //if ((i > 0) && (i % 14 == 0))
      //EinkDisplay.println();
  }    
  EinkDisplay.refresh();
}
</pre>

**Comment by Andy2No** [comment]
I see some of that gets mangled, by trying to post it with "pre" tags.  I assumed github comments would support the CODE tags, like any forum with bbcodes, but it doesn't.  Instead, big chunks of it get removed, between angled brackets.

 It seems I can't just attach the file without renaming it or putting it in a zip, either.... So, here it is, renamed from .ino to .txt:

[GFX_demo.txt](https://github.com/mvniemi/Linksprite_EP2P04/files/993113/GFX_demo.txt)

**Comment by mvniemi** [comment]
Hey Andy,
I've pushed a couple of fixed examples along with an updated library. You were absolutely right about the buffer declarations, that was an old test version and they should now be allocated dynamically (watch out with the memory!). You will need to replace the old library with the new one.

The two examples have the proper constructor calls (you don't have to declare all the arguments first), and they both work on my Leonardo, let me know if you have issues. 

You are absolutely right about it being flaky with the refreshing. It seems like sometimes you need to either add a delay or call refresh multiple times to get it to go, and then other times it seems to not have an issue. This is my first time working with an SPI display like this, so I wasn't aware that you can check the display status, definitely worth looking into. If you are able to make any improvements to the library or have cool example files, I'd love to add them to the repo.

 I need to get it running on a Mega, as I think the 4-tone color definitely adds a lot (you can see it in the demo image of my github character). It's interesting that they come stock with that nametag logo, I think these displays are used for price tag labels in supermarkets and are quite cheap, it would be nice to see the breakout-board at a lower price.

**Comment by Andy2No** [comment]
EDIT:  Sorry, I've only just seen your last post, after posting this...  I'll look at your updates soon, and try it in 4 tone mode :)  Thanks.

I've got a bit further with it, after much hair pulling.

I was having to press the reset button on the Leonardo almost every time, then wait for it to decide it wasn't going to be asked to upload a sketch, and I determined that the display was going to sleep after a very short while, so I couldn't get many of the steps to work.

I moved it to an Uno - not enough memory - then to a Mega 2560, thinking that would at least shorten the loop to test changes.  It didn't.  It was a lot more awkard.  Even the reset button or unplugging it wouldn't restart the display - it was just frozen, most of the time.

I think I've figured out a problem because of that though - in both the manufacturers "luggage label" demo (minieink), and your library, as I've seen it so far, the RS aka RES or Reset pin 12, isn't set as an output, and it seems it needs to be to work consistently - or sometimes at all.

Rather than mess with your library code, I copied chunks of it into the demo sketch, so I had access to the private functions.  After setting RS as an output, and doing the initialisation again, it worked flawlessly... Apart from the nature of display updates, which seem to be fixed at no more than once every two or three seconds, no matter how often you ask for them in the code.

I've attached a more working demo, as a txt file - rename it to a .ino, of course.  

Big chunks of it could be removed, if you initialise the RS pin (12), along with the others, as an output,  I also held the RS line low for longer (100ms), but that might not be needed - I tried that first, before I realised the pin wasn't set as an output.
[GFX_demo_experiments.txt](https://github.com/mvniemi/Linksprite_EP2P04/files/994627/GFX_demo_experiments.txt)

**Comment by mvniemi** [comment]
Definitely reinstall the library and try the new demo sketches, they are working for me no problem with on a Leonardo. I think the version you are working with has memory issues.  Good catch with the RS pin, I kind of just ported over the manufacture code and didn't pay too much attention, I'll change that in the library. Apologies again for pushing my buggy code in the first place, I had intended to get the proper version up but got busy.

In terms of the display updates, perhaps a delay should be built into the refresh function?

**Comment by Andy2No** [comment]
No problem.

I think it might be partly / largely due to an initialisation problem, though I added bits in that demo code to check that the busy flag was clear and wait for it.  I made it show on the Tx LED, because 13 is in use as SCK.  I only see brief flashes, but they're long enough to be noticeable, so I guess that means the wait was justified.

Re, the init: I hadn't noticed but I still wasn't getting a reset when I plugged the USB cable into the Mega (e.g. just to power it up), but I seem to have fixed that by waiting longer after a reset, via the RS pin:

- I kept the pin low for 100ms, then waited that long again, after releasing it.  It now resets as expected, not just on uploading the sketch:

<pre>
void eInkReset()  // Linksprite_EP2P04::RESET() is private so copied here
{
  // precede this with:
  // pinMode(RS,OUTPUT); 
  
    digitalWrite(RS,LOW); // nRST_L;
    eInkDelayShowingStatusLED(100); // DELAY_mS(1);//1ms - try longer, just to make sure
    digitalWrite(RS,HIGH); // nRST_H;
    eInkDelayShowingStatusLED(100); // DELAY_mS(1);//1ms - try longer.  Seems to help - didn't get a reeset plugging in cable before

    //SPI4W_WRITEDATA(0x12);  // Try a Software RESET - doesn't seem to be needed
}
</pre>

I've been at this a bit too long, so I may well make a mess of installing your new library :)  I'll come back to it a bit later.

**Comment by Andy2No** [comment]
I forgot to ask; have you seen the datasheet for the display driver chip?  It's not all that clear, but better than nothing:

http://www.good-display.com/download_detail/downloadsId=165.html

**Comment by Andy2No** [comment]
Well, that's odd.  Now I don't see the Tx LED flash at all (still on the old library)... and it's still not resetting consistently, when I plug the cable in.  Oh well.  The datasheet doesn't appear to say how long to hold the reset for.  Normally, they do. 

EDIT:
It seems the Tx LED thing is a red herring - apparently it can't be controlled by the main chip.  I guess it must have been the serial port doing something.  I started with the LED on pin 13, but it seemed like asking for trouble, since it's in use as SCK, plus of course, it lights during transfers, so it's not clear when it's showing the status.  I'll add an external LED tomorrow.

**Comment by Andy2No** [comment]
I've now installed the new library and examples, and tried to run them on the Mega.  Bit of a problem with that - the reset / initialisation problem is still there.  

I tried all three examples, but I've only seen the GFX_demo one run, so far, and only one time out of three - they don't reset the display after uploading the sketch, and not normally after pressing the physical reset button either, oddly.

The file I attached yesterday still works with the new library.  I added an external status LED, which is on for longish periods up to the point where it draws the face.   The STAT/Busy pin wasn't being checked all of the time, of course.  I haven't decided how useful that is yet :)  Quite possibly, I've made a mistake in the code that's checking it.

Anyway, have a look at my code, especially the changes to initialisation.  A lot of it is just copying bits of the private member functions so I could use it without editing the library.  Once you eliminate all that, there's only a few changes.

 I notice in Linksprite_EP2P04::Linksprite_EP2P04(...) you're still missing:

    pinMode(_rs,OUTPUT);

and that might be all it takes.   Using a pin as an output before setting it as one, has odd results.

I also held the display driver chips reset (RS) line low longer, and then waited a short while after that, to give the chip time to boot up before anything else was allowed to happen.  I've no idea if that was needed, because I couldn't find anything about it in the datasheet, but it's the sort of procedure that display driver chips tend to require.

    digitalWrite(RS,LOW); // nRST_L;
    eInkDelayShowingStatusLED(100); // DELAY_mS(1);//1ms - try longer, just to make sure
    digitalWrite(RS,HIGH); // nRST_H;
    eInkDelayShowingStatusLED(100); // DELAY_mS(1);//1ms - try longer.  Seems to help - didn't get a reeset plugging in cable before

In your case, that would be _rs, or using those macros, and maybe you'd just use delay(100)

About adding delays - I think it's valid to wait during initialisation, but generally, the user code should have the information and the choice - i.e, a public function to check the busy status, and where functions might need to wait for the status to change, it would be good to provide a timeout parameter; e.g.

    max_wait= 5; // don't want to wait around for more than 5 milliseconds; things to do
    EinkThingy.refresh(max_wait);

It seems likely that a 16MHz CPU doesn't need to wait much, but if the code was used on a faster chip, not waiting for the Busy flag to turn off could become a problem.

**Comment by mvniemi** [comment]
I've made a couple of changes to the library. RS is now set as an output pin, and the RESET() and INIT() functions are public, with RESET() having and optional int parameter for the delay, which I've also set the default value to 100. I'm a bit perplexed by the initiation problems you're having, as all three sketches work fine and reliably with my Leonardo and Mini even when the delay was only 1ms.

Additionally, in the refresh() function I have put in a while loop to block in STAT is high. This seems to have solved the issue of not getting a refresh in some of my test cases, so I'm assuming this is the proper usage of the STAT pin. Let me know if you see improvements, any use of the STAT pin was missing in the factory example because they only worried about writing the buffer once. If this is the case we don't have to worry about specifying a delay time, though we can still add a max delay (I can't imagine it actually blocks for that long?).

**Comment by Andy2No** [comment]
Thanks.  Yes, that's working well, and resets are now working as they should with your GFX_demo and serial_type test sketches on the Mega 2560 - on plugging in a USB cable for power, on pressing the reset button on the Mega and on opening the serial monitor / terminal from inside the Arduino IDE.

The write_buffer_only.ino sketch still has the same reset issues - it basically doesn't want to reset under any of those circumstances and it's more of a fluke when it works.  I don't understand why it works better on the Leonardo either but it is different hardware.  I notice the official page about the Mega 2560 R3 talks about an improved reset circuit.  Maybe that's part of the problem.

Anyway, yes, the new changes do solve the reset problem - the write_buffer_only sketch doesn't use your library, of course.

As for waiting, the worst case scenario would be the Arduino having to wait during the entire screen refresh done by the display chip, if it sits waiting for the STAT flag to change.  Depending on the application, that might not matter, but it is quite a long time, so it's best if the user code gets to make the decision whether to wait or to get on with doing something else.  

So long as it knows it can't do any more screen operations until the display chip has finished, it doesn't need to just wait.  The simplest way of doing that is to make the refresh() a request, not an order - i.e. calling it is a way of saying you'd like a refresh done, not that it has to be done, and an optional timeout parameter to say how long you're prepared to wait seems reasonable.  Returning a status code to say whether or not the refresh was done would be useful.

So, instead of just waiting for the busy flag to clear at the start of reset() with

   while(read_stat)  ;  // wait forever, if needed

do something like

  unsigned long start_time= millis();
  while(read_stat && (millis() - start_time < max_waiting_time))  ;  // be less patient
  if(!read_stat)
  { 
     // do the refresh
    return status_success;
  }
  else return status_timed_out;

Incidentally, it should be possible to write directly to the display chips own memory, rather than write incrementally to a buffer then send the whole buffer.  There'll be overheads on each write, so it wouldn't always improve performance.  It could potentially mean operating without a big chunk of memory allocated to the screen buffer though.  

The display chip has a start x and y address (as set in the init function), which is used for the transfer, ending with the 0x20 command, which I guess triggers the refresh.  It should be possible to send commands to set the coordinate, then send a pixel or a short run of them.  There's probably no need to send the 0x20 every time.  There's a NULL command you could use to end a transfer, for example.

I'm not suggesting you should do it that way, just that it's a possible way of doing things.  I'm sure most people will be happy just to get their display useable and reliable anyway.

**Comment by mvniemi** [comment]
I've updated the refresh() function so that it now has a timeout with an optional parameter and returns a bool based on the success. The default timeout is set at 200ms, very interestingly I was seeing timeouts at 100ms when calling the circle function. That kind of delay could wreck havoc on a lot of embedded peripherals, so a time sensitive sketch would probably need to set the timeout very low and call refresh on a schedule.

Very interesting with writing to the display memory, I was not aware of those capabilities and assumed you had to write to the display all at once, but that is definitely not the case. I finally looked at the datasheet and it has ~12k display memory with capacity to have double display buffers. There's also apparently the option to choose the scanning mode of the display, which can make the bit math a little more straightforward by scanning horizontally versus vertically. 

Given that e-paper is ideal for low power applications which consequently will also use low power microcontrollers, I think it's probably worth it to change the library to use the onboard buffer instead, not to mention it makes 4 tone greyscale available. Because the AdaFruit library works setting one pixel at a time, it will add some overhead (set the address, read the current byte, perform bit arithmetic, write the byte), but it will be linear. It should actually save time on something like writing a single character and then refreshing, as the current library copies over the entire buffer over just to make even a single pixel change.

**Comment by Andy2No** [comment]
Cool.  Yes, writing the whole buffer is a lot of work, and must take a while, so writing directly seems like a better way to go.

What you have already constitutes a working library though, so maybe it's time to declare that a release and bump the version number up for the new one - I'm sure anyone who's just got hold of this display will be happy with your library the way it is, for now, so they can see it working and maybe get some use out of it.

**Comment by mvniemi** [comment]
I did some reading through the SPD2701 datasheet, and unfortunately, the chip does not support reading from the onboard buffer through serial mode (SPI, etc.), only a parallel connection which the breakout board is not even pinned for. Sadly this means writing pixel by pixel to the buffer is not possible as we don't know what the other three pixels on each byte are without being able to read them. Selective writing of the Arduino buffer to the board to only include changed areas is a possibility, however, my suspicion is that the real speed bottleneck is that the e-paper refresh rate is inherently slow.

I went ahead and gave it a release number. Thanks again for your help!

**Comment by Andy2No** [comment]
Yes, I see what you mean.  You'd think there'd be a write mask, to let you leave the other bits in the byte alone.  If it can't be done without a RAM buffer on the Arduino, there's probably not much point changing it

Oddly, the datasheet labels the pins for the SPI interface as SDA and SCL, which is I2C, not SPI.

Anyway, good work.  If people want to use e-ink/e-paper, and have owned an e-book that uses it, they won't be too surprised at how long it takes to refresh.  There are plenty of applications where a microcontroller is just sat waiting for user input most of the time, anyway.
