### ISSUE TITLE
#include <util/delay.h> not found for esp8266 or esp32

### ISSUE THREAD

**Issue by Atzingen** [mvniemi/Linksprite_EP2P04#2]
The examples don't compile for esp boards.
I have made a fix (basicaly two problens: one is the _delay_ms that the esp compiler does not have and the other is the progmemory use on esp, that needs a esp library for that. 
Can I submit a pull request ?  Or you Just need to change the main .cpp file from this library with this:

#include "Linksprite_EP2P04.h"
#if defined(ESP32)
  #include <pgmspace.h>
  #define _delay_ms(ms) delayMicroseconds((ms) * 1000)
#endif
#if defined(ESP8266)
  #include <pgmspace.h>
  #define _delay_ms(ms) delayMicroseconds((ms) * 1000)
#endif
#ifdef __avr__
  #include <util/delay.h>
#endif

Thanks for the library !

**Comment by mvniemi** [comment]
Hey Gustavo,
Thanks so much for your contribution and my apologies for the delay in responding. I went ahead and merged your pull request, and feel free to submit any further improvements you might make, especially if you have any interesting example uses!
